{% set name = "breadability" %}
{% set version = "0.1.20" %}
{% set py_ver = PY_VER %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/breadability-{{ version }}.tar.gz
  sha256: f1a7fdad1e58e295df80954879143824c706bbfb1826cdf4b1d15de1a86afe99

build:
  number: 1
  noarch: python
  entry_points:
    - breadability = breadability.scripts.client:main
    - breadability-{{ py_ver }} = breadability.scripts.client:main
    - breadability_test = breadability.scripts.test_helper:main
    - breadability_test-{{ py_ver }} = breadability.scripts.test_helper:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - chardet
    - docopt >=0.6.1,<0.7
    - lxml >=2.0
    - python >={{ python_min }}

test:
  imports:
    - breadability
  commands:
    - pip check
    - breadability --help
    - breadability-{{ py_ver }} --help
    - breadability_test --help
    - breadability_test-{{ py_ver }} --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bookieio/breadability
  summary: Port of Readability HTML parser in Python
  license: BSD-2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - nicornk
    - tobiasploetz
